### ISSUE TITLE
First-time text in stage 2 has changed

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/factorial-design-breathing-study#15]
The text participants see the first time they do stage 2 (in section "Stage 2: Paced breathing according to condition at home/Experimental explanation - first time use only" of the spec) has changed to remind participants to breathe in through their nose. The app should reflect this change.

**Comment by noah10** [comment]
Note that if you have already seen the first-time instructions in stage 2 you will need to switch to a new condition that deletes all of your data in order to test this.

**Comment by choipaul92** [comment]
Ver: 1.0.5.

Text has been updated to reflect breathing in through their nose during Stage 2 prior to their first 18 minute session

Note: I cannot close this issue because I am not the author 

![IMG_1437](https://github.com/EmotionCognitionLab/factorial-design-breathing-study/assets/89946691/5c1ec69a-4a58-4e10-a9b6-da918000eedd)
