### ISSUE TITLE
Payment does not reflect the accurate amount

### ISSUE THREAD

**Issue by juliana-20** [EmotionCognitionLab/factorial-design-breathing-study#23]
Payment does not reflect the accurate amount received based on completed number of sessions. Discussed with Noah and he suggested to open a Github issue.

![IMG_2268](https://github.com/EmotionCognitionLab/factorial-design-breathing-study/assets/127356600/84f9b8ab-309e-4b5a-8c48-2bced2b08c0b)

**Comment by noah10** [comment]
This should be fixed in v1.0.3.

**Comment by choipaul92** [comment]
Update: My earnings for are correct. While I am in the performance condition, I think my bonuses are $0 because of my coherence score not because of a bug.

I have completed 3 days of practices with two 18 minute sessions ea/ day. 

![IMG_1416](https://github.com/EmotionCognitionLab/factorial-design-breathing-study/assets/89946691/84be19fb-5bf1-4994-bca1-15c0579a6f09)

**Comment by choipaul92** [comment]
After completing my first session for Day 4, I checked the earnings dashboard & my earnings + bonus for today was updated immediately!

**Comment by juliana-20** [comment]
Update - It looks like payment is correct. After completing two sessions today, I received $8 and $4 in bonus ($0 bonus from 1st session and $4 from session 2).
