### ISSUE TITLE
Breathing pacer not shown during 18-minute session in condition 3

### ISSUE THREAD

**Issue by juliana-20** [EmotionCognitionLab/factorial-design-breathing-study#6]
At times, the breathing pacer is not shown accurately to begin the 18-minute session. In one example, the breathing pacer did not display at the start of the session. It worked after exiting and reopening and the app. In another example, after pausing to take a break in the middle of the 18-minute session, the app did not display the breathing pacer to restart the session from the beginning. Exiting and reopening the app after a few attempts did not work. Instead, it worked after completely closing the app and waiting for about 20 minutes to begin again.

**Comment by noah10** [comment]
In at least one case this turned out to be because the breathing pace was set to null in the user data. That does not explain why it sometimes *did* appear, though - with a null breathing pace I would expect it never to be visible.

**Comment by noah10** [comment]
This just happened to me, and the problem was that I was apparently attempting to do a regime less than 10 seconds long (which is the minimum length, from breath-pacer-utils.js). Need to look into why that was happening.

**Comment by noah10** [comment]
I believe there were two separate problems here: In one, the participant did not have any breathing pace set. That's likely due to some issue with deletion of data during testing. The second one was that the app did not properly check to see if the user was finished for the day, causing it to try to have them breathe for something impossible like -1 minutes. That has now been fixed in v1.0.3.

**Comment by juliana-20** [comment]
Issue resolved - app informs the user that they are done for the day after completing two sessions (18-minutes each).
